// <auto-generated />
using System;
using FiscalService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiscalService.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424145436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiscalService.Api.Data.Entities.EmissaoLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ambiente");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoStatus")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_status");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_processamento");

                    b.Property<string>("MensagemStatus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem_status");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("modelo");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("XmlPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("xml_path");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcesso")
                        .HasDatabaseName("ix_emissao_logs_chave_acesso");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_emissao_logs_status");

                    b.HasIndex("Cnpj", "DataEmissao")
                        .HasDatabaseName("ix_emissao_logs_cnpj_data");

                    b.ToTable("emissao_logs");
                });

            modelBuilder.Entity("FiscalService.Api.Data.Entities.NumeracaoSequencial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("modelo");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("serie");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_atualizacao");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_numero");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj", "Modelo", "Serie")
                        .IsUnique()
                        .HasDatabaseName("ix_numeracoes_cnpj_modelo_serie");

                    b.ToTable("numeracoes_sequenciais");
                });
#pragma warning restore 612, 618
        }
    }
}
